title: Rafal M Cichon
#logo: /assets/img/logo.png
description: Digital Resume.
show_downloads: false
#google_analytics: UA-1000-1
#theme: jekyll-theme-minimal

#email: rafalmcichon@gmail.com
#author:
#  name: Rafal M Cichon
#  email: rafalmcichon@gmail.com
#plugins:
#  - jekyll-feed
#  - jekyll-seo-tag
